<a href="https://colab.research.google.com/github/LxYuan0420/eat_tensorflow2_in_30_days/blob/master/notebooks/4_1_Structural_Operations_of_the_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**4-1 Structural Operations of the Tensor**

Tensor operation includes structural operation and mathematical operation.

The structural operation includes tensor creation, index slicing, dimension transform, combining & splitting, etc.

The mathematical operation includes scalar operation, vector operation, and matrix operation. We will also introduce the broadcasting mechanism of tensor operation.

This section is about the structural operation of tensor.

**1. Creating Tensor**

Tensor creation is similar to array creation in numpy.

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = tf.constant([1,2,3], dtype=tf.float32)
tf.print(a)

[1 2 3]


In [3]:
b = tf.range(1, 10, delta=2)
tf.print(b)

[1 3 5 7 9]


In [4]:
c = tf.linspace(0.0, 2*3.14, 100)
tf.print(c)

[0 0.0634343475 0.126868695 ... 6.15313148 6.21656609 6.28]


In [5]:
d = tf.zeros([3,3])
tf.print(d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
a = tf.ones([3,3])
b = tf.zeros_like(a, dtype=tf.float32)
tf.print(a)
tf.print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
b = tf.fill([3,2], 5)
tf.print(b)

[[5 5]
 [5 5]
 [5 5]]


In [9]:
#radnom numbers with uniform distribution
tf.random.set_seed(1.0)
a = tf.random.uniform([5], minval=0, maxval=10)
tf.print(a)

[1.65130854 9.01481247 6.30974197 4.34546089 2.9193902]


In [10]:
b = tf.random.normal([3,3], mean=0.0, stddev=1.0)
tf.print(b)

[[0.403087884 -1.0880208 -0.0630953535]
 [1.33655667 0.711760104 -0.489286453]
 [-0.764221311 -1.03724861 -1.25193381]]


In [11]:
c = tf.random.truncated_normal((5,5), mean=0.0, stddev=1.0, dtype=tf.float32)
tf.print(c)

[[-0.457012236 -0.406867266 0.728577733 -0.892977774 -0.369404584]
 [0.323488563 1.19383323 0.888299048 1.25985599 -1.95951891]
 [-0.202244401 0.294496894 -0.468728036 1.29494202 1.48142183]
 [0.0810953453 1.63843894 0.556645 0.977199793 -1.17777884]
 [1.67368948 0.0647980496 -0.705142677 -0.281972528 0.126546144]]


In [12]:
I = tf.eye(3,3)
tf.print(I)
tf.print(" ")
t = tf.linalg.diag([1,2,3])
tf.print(t)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
 
[[1 0 0]
 [0 2 0]
 [0 0 3]]


**2. Indexing and Slicing**

The indexing and slicing of tensor is the same as numpy, and slicing supports default parameters and ellipsis.

Data type of tf.Variable supports indexing and slicing to modify values of certain elements.

For referencing a continuous portion of a tensor, tf.slice is recommended.

On the other hand, for the irregular slicing shape, tf.gather, tf.gather_nd, tf.boolean_mask are recommended.

The method tf.boolean_mask is powerful, it functions as both tf.gather and tf.gather_nd, and supports boolean indexing.

For the purpose of creating a new tensor through modifying certain elements in an existing tensor, tf.where and tf.scatter_nd can be used.

In [13]:
tf.random.set_seed(3)

t = tf.random.uniform([5,5], minval=0, maxval=10, dtype=tf.int32)
tf.print(t)

[[4 7 4 2 9]
 [9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]
 [3 7 0 0 3]]


In [14]:
#row 0 
tf.print(t[0])

[4 7 4 2 9]


In [15]:
tf.print(t[-1])

[3 7 0 0 3]


In [16]:
tf.print(t[1,3])

4


In [18]:
#from row1 to row3
tf.print(t[1:4, :])

#tf.slice(input, begin_vector, size_vector)
tf.print(tf.slice(t, [1,0], [3,5]))

[[9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]]
[[9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]]


In [20]:
#from row 1 to the last row, and from column 0 to the last but one with an increment of 2
tf.print(t[1:4, :4:2])

[[9 2]
 [7 7]
 [9 9]]


In [21]:
#variable supports modifying elemnts thru indexing and slicing
x = tf.Variable([[1,2], [3,4]], dtype=tf.float32)
x[1,:].assign(tf.constant([0.0,0.0]))
tf.print(x)

[[1 2]
 [0 0]]


In [22]:
a = tf.random.uniform([3,3,3], 0, 10, dtype=tf.int32)
tf.print(a)

[[[7 3 9]
  [9 0 7]
  [9 6 7]]

 [[1 3 3]
  [0 8 1]
  [3 1 0]]

 [[4 0 6]
  [6 2 2]
  [7 9 5]]]


In [23]:
# ellipsis represnts multiple colons
tf.print(a[...,1])


# this is equal to 
tf.print(a[:,:,1])

[[3 0 6]
 [3 8 1]
 [0 2 9]]
[[3 0 6]
 [3 8 1]
 [0 2 9]]


The examples above are regular slicing; for irregular slicing, tf.gather, tf.gather_nd, tf.boolean_mask can be used.

Here is an example of student's grade records. There are 4 classes, 10 students in each class, and 7 courses for each student, which could be represented as a tensor with a dimension of 4×10×7.

In [26]:
scores = tf.random.uniform((4,10,7), minval=0, maxval=100, dtype=tf.int32)
tf.print(scores)

[[[0 64 96 ... 65 28 30]
  [16 99 74 ... 26 5 39]
  [12 48 9 ... 34 76 10]
  ...
  [70 79 37 ... 72 38 31]
  [65 55 44 ... 31 23 64]
  [88 59 9 ... 64 66 92]]

 [[11 24 9 ... 16 35 59]
  [46 46 87 ... 38 62 36]
  [37 52 47 ... 2 51 48]
  ...
  [74 95 6 ... 49 9 54]
  [67 47 74 ... 11 68 6]
  [92 29 27 ... 59 99 71]]

 [[78 37 24 ... 54 9 79]
  [77 99 5 ... 97 53 84]
  [25 26 89 ... 74 22 75]
  ...
  [94 67 77 ... 97 56 38]
  [61 44 50 ... 72 87 44]
  [48 67 96 ... 60 23 82]]

 [[64 74 80 ... 49 58 12]
  [19 51 31 ... 57 39 67]
  [16 31 46 ... 94 50 13]
  ...
  [20 81 89 ... 4 85 66]
  [90 19 14 ... 99 27 96]
  [35 63 52 ... 34 59 64]]]


In [27]:
# extract all the grades of the 0th, 5th, 9th students in each class.
p = tf.gather(scores, [0, 5, 9], axis=1)
tf.print(p)

[[[0 64 96 ... 65 28 30]
  [43 38 66 ... 7 7 65]
  [88 59 9 ... 64 66 92]]

 [[11 24 9 ... 16 35 59]
  [94 3 55 ... 4 93 52]
  [92 29 27 ... 59 99 71]]

 [[78 37 24 ... 54 9 79]
  [95 17 83 ... 99 84 96]
  [48 67 96 ... 60 23 82]]

 [[64 74 80 ... 49 58 12]
  [82 71 32 ... 49 39 28]
  [35 63 52 ... 34 59 64]]]


In [28]:
# extract the grades of the 1st, 3rd and 6th courses of the 0th, 5th, 9th students in each class
q = tf.gather(tf.gather(scores, [0,5,9], axis=1), [1,3,6], axis=2)
tf.print(q)

[[[64 49 30]
  [38 4 65]
  [59 25 92]]

 [[24 58 59]
  [3 30 52]
  [29 76 71]]

 [[37 59 79]
  [17 0 96]
  [67 84 82]]

 [[74 83 12]
  [71 36 28]
  [63 84 64]]]


In [29]:
# Extract all the grades of the 0th student in the 0th class, the 4th student in the 2nd class, and the 6th student in the 3rd class.
# Then length of the parameter indices equals to the number of samples, and the each element of indices is the coordinate of each sample.
s = tf.gather_nd(scores, indices=[(0,0), (2,4), (3,6)])
s

<tf.Tensor: shape=(3, 7), dtype=int32, numpy=
array([[ 0, 64, 96, 49, 65, 28, 30],
       [58, 58, 96, 59, 51, 33, 64],
       [ 8, 43, 24, 71, 87, 79, 10]], dtype=int32)>

In [30]:
#extract all the grades of the 0th, 5th, and 9th students in each class
p = tf.boolean_mask(scores, [True, False, False, False, False, True, False, False, False, True], axis=1)
tf.print(p)

[[[0 64 96 ... 65 28 30]
  [43 38 66 ... 7 7 65]
  [88 59 9 ... 64 66 92]]

 [[11 24 9 ... 16 35 59]
  [94 3 55 ... 4 93 52]
  [92 29 27 ... 59 99 71]]

 [[78 37 24 ... 54 9 79]
  [95 17 83 ... 99 84 96]
  [48 67 96 ... 60 23 82]]

 [[64 74 80 ... 49 58 12]
  [82 71 32 ... 49 39 28]
  [35 63 52 ... 34 59 64]]]


In [31]:
# Boolean indexing using tf.boolean_mask

# Find all elements that are less than 0 in the matrix
c = tf.constant([[-1,1,-1],[2,2,-2],[3,-3,3]],dtype=tf.float32)
tf.print(c,"\n")

tf.print(tf.boolean_mask(c,c<0),"\n") 
tf.print(c[c<0]) # This is the syntactic sugar of boolean_mask for boolean indexing.

[[-1 1 -1]
 [2 2 -2]
 [3 -3 3]] 

[-1 -1 -2 -3] 

[-1 -1 -2 -3]


The methods shown above are able to extract part of the elements in the tensor, but are not able to create new tensors through modification of these elements.

The method tf.where and tf.scatter_nd should be used for this purpose.

tf.where is the tensor version of if; on the other hand, this method is able to find the coordinate of all the elements that statisfy certain conditions.

tf.scatter_nd works in an opposite way to the method tf.gather_nd. The latter collects the elements according to the given coordinate, while the former inserts values on the given positions in an all-zero tensor with a known shape.



In [32]:
c = tf.constant([[-1,1,-1], [2,2,-2], [3,-3,3]], dtype=tf.float32)
d = tf.where(c<0, tf.fill(c.shape, np.nan), c)
d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[nan,  1., nan],
       [ 2.,  2., nan],
       [ 3., nan,  3.]], dtype=float32)>

In [33]:
indices = tf.where(c<0)
indices

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[0, 0],
       [0, 2],
       [1, 2],
       [2, 1]])>

In [34]:
# The method scatter_nd functions inversly to gather_nd
# This method can be used to insert values on the given positions in an all-zero tensor with a known shape.
indices = tf.where(c<0)
tf.scatter_nd(indices,tf.gather_nd(c,indices),c.shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.,  0., -1.],
       [ 0.,  0., -2.],
       [ 0., -3.,  0.]], dtype=float32)>

**3. Dimension Transform**

The functions that are related to dimension transform include tf.reshape, tf.squeeze, tf.expand_dims, tf.transpose.

tf.reshape is used to alter the shape of the tensor.

tf.squeeze is used to reduce the number of dimensions.

tf.expand_dims is used to increase the number of dimensions.

tf.transpose is used to exchange the order of the dimensions.

tf.reshape changes the shape of the tensor, but will not change the order of elements stored in the memory, thus this operation is extremely fast and reversible.

In [36]:
a = tf.random.uniform(shape=[1,3,3,2], minval=0, maxval=255, dtype=tf.int32)

tf.print(a)
tf.print(a.shape)

[[[[225 223]
   [22 182]
   [163 8]]

  [[37 235]
   [36 107]
   [63 204]]

  [[76 177]
   [90 167]
   [69 96]]]]
TensorShape([1, 3, 3, 2])


In [37]:
b =tf.reshape(a, [3,6])
tf.print(b.shape)
tf.print(b)

TensorShape([3, 6])
[[225 223 22 182 163 8]
 [37 235 36 107 63 204]
 [76 177 90 167 69 96]]


In [38]:
#reshape back to (1,3,3,2)
c = tf.reshape(a, (1,3,3,2))
tf.print(c)

[[[[225 223]
   [22 182]
   [163 8]]

  [[37 235]
   [36 107]
   [63 204]]

  [[76 177]
   [90 167]
   [69 96]]]]


When there is only one element on a certain dimension, tf.squeeze eliminates this dimension.

It won't change the order of the stored elements in the memory, which is similar to tf.reshape.

The elements in a tensor is stored linearly, usually the adjacent elements in the same dimension use adjacent physical addresses.

In [39]:
s = tf.squeeze(a)
tf.print(s.shape)
tf.print(s)

TensorShape([3, 3, 2])
[[[225 223]
  [22 182]
  [163 8]]

 [[37 235]
  [36 107]
  [63 204]]

 [[76 177]
  [90 167]
  [69 96]]]


In [41]:
d = tf.expand_dims(s, axis=0)
d

<tf.Tensor: shape=(1, 3, 3, 2), dtype=int32, numpy=
array([[[[225, 223],
         [ 22, 182],
         [163,   8]],

        [[ 37, 235],
         [ 36, 107],
         [ 63, 204]],

        [[ 76, 177],
         [ 90, 167],
         [ 69,  96]]]], dtype=int32)>

tf.transpose swaps the dimensions in the tensor; unlike tf.shape, it will change the order of the elements in the memory.

tf.transpose is usually used for converting image format of storage.

In [42]:
# Batch,Height,Width,Channel
a = tf.random.uniform(shape=[100,600,600,4],minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)

# Transform to the order as Channel,Height,Width,Batch
s= tf.transpose(a,perm=[3,1,2,0])
tf.print(s.shape)

TensorShape([100, 600, 600, 4])
TensorShape([4, 600, 600, 100])


**4. Combining and Splitting**

We can use tf.concat and tf.stack methods to combine multiple tensors, and use tf.split to split a tensor into multiple ones, which are similar as those in numpy.

tf.concat is slightly different to tf.stack: tf.concat is concatination and does not increase the number of dimensions, while tf.stack is stacking and increases the number of dimensions.

In [43]:
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

tf.concat([a,b,c],axis = 0)

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]], dtype=float32)>

In [44]:
tf.concat([b,c], axis=1)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 5.,  6.,  9., 10.],
       [ 7.,  8., 11., 12.]], dtype=float32)>

In [45]:
tf.stack([a,b,c])

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)>

In [46]:
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

c = tf.concat([a,b,c],axis = 0)

tf.split is the inverse of tf.concat. It allows even splitting with given number of portions, or uneven splitting with given size of each portion.

In [48]:
tf.split(c, 3, axis=0)

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[5., 6.],
        [7., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 9., 10.],
        [11., 12.]], dtype=float32)>]

In [50]:
tf.split(c, [2,2,2], axis=0)

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[5., 6.],
        [7., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 9., 10.],
        [11., 12.]], dtype=float32)>]